################################################################################
# This workflow will do a clean install of node dependencies, build the source
# code and run tests across different versions of node.
#
# For more information see:
#
#   https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#
################################################################################

name: Node.js CI

# Controls when the action will run. Triggers the workflow on push or pull
# request events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: Linux
            node-version: 14
          #- os: macOS
          #  node-version: 14
          #- os: ubuntu-16.04
          #  node-version: 12
          #- os: ubuntu-18.04
          #  node-version: 12
          #- os: ubuntu-20.04
          #  node-version: 14

    # Steps represent a sequence of tasks that will be executed as part of the
    # job
    steps:
      - name: Build environment information
        run: 'echo "Matrix OS: ${{ matrix.os }} on $HOSTNAME with $(getconf _NPROCESSORS_ONLN) cores"'

        # Check-out the repository under $GITHUB_WORKSPACE, so the job can
        # access it
      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore node modules
        id: restore-node
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            package-lock.json
          key: npm-install-${{ matrix.node-version }}-${{ matrix.os }}-${{ hashFiles('package.json', 'tools/npm-install.sh') }}

      # npm ci is required, instead of npm install, because we recursively
      # patch sub-dependencies in the post-install step and require correct
      # versions for the patches to apply.
      #
      # However, although package-lock.json is generated and updated in the
      # preinstall step, npm ci won't run if package-lock.json doesn't exist
      # yet. Chicken, meet egg.
      #
      # To get around this, manually run the preinstall step once evey time
      # the project is cleaned:
      #
      #   npm run preinstall
      #
      # Instead of npm install, run:
      #
      #   npm ci
      #
      - name: npm run preinstall
        if: steps.restore-node.outputs.cache-hit != 'true'
        run: npm run preinstall

      - name: npm ci
        if: steps.restore-node.outputs.cache-hit != 'true'
        run: npm ci

      - name: npm run audit
        run: npm run audit

      - name: Restore OpenCV library
        id: restore-opencv
        uses: actions/cache@v2
        with:
          path: |
            src/generated/opencv.js
            tools/dist
          key: restore-opencv-${{ matrix.os }}-${{ hashFiles('tools/depends/ade/*', 'tools/depends/ceres-solver/*', 'tools/depends/eigen/*', 'tools/depends/emscripten/*', 'tools/depends/google-flags/*', 'tools/depends/google-log/*', 'tools/depends/opencv/*') }}

      - name: Restore C++ libraries
        id: restore-libraries
        uses: actions/cache@v2
        with:
          path: |
            public/motion_tracker/motion_tracker.js
            public/motion_tracker/motion_tracker.wasm
          key: restore-libraries-${{ matrix.os }}-${{ hashFiles('lib/*', 'lib/**/*', 'tools/depends/ade/*', 'tools/depends/ceres-solver/*', 'tools/depends/eigen/*', 'tools/depends/emscripten/*', 'tools/depends/google-flags/*', 'tools/depends/google-log/*', 'tools/depends/opencv/*') }}

      - name: Restore dependency libraries
        id: restore-library-depends
        uses: actions/cache@v2
        if: steps.restore-libraries.outputs.cache-hit != 'true' || steps.restore-opencv.outputs.cache-hit != 'true'
        with:
          path: |
            tools/dist
          key: restore-library-depends-${{ matrix.os }}-${{ hashFiles('tools/depends/ade/*', 'tools/depends/ceres-solver/*', 'tools/depends/eigen/*', 'tools/depends/emscripten/*', 'tools/depends/google-flags/*', 'tools/depends/google-log/*', 'tools/depends/opencv/*') }}

      - name: Build depends
        run: npm run depends

      - name: npm run compile
        run: npm run compile

      - name: npm test
        run: npm test

      - name: npm run build
        run: npm run build
