################################################################################
# This workflow will do a clean install of node dependencies, build the source
# code and run tests across different versions of node.
#
# For more information see:
#
#   https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#
################################################################################

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x, 14.x]
        os: [ubuntu-20.04]

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore dependency repos
        id: cache-repos
        uses: actions/cache@v2
        with:
          path: |
            tools/repos
          key: checkout-${{ hashFiles('tools/manifest.mk') }}

      - name: Checkout Emscripten SDK repo
        uses: actions/checkout@v2
        if: steps.cache-repos.outputs.cache-hit != 'true'
        with:
          repository: 'emscripten-core/emsdk'
          ref: '1.39.18'
          path: tools/repos/emsdk

      - name: Checkout OpenCV repo
        uses: actions/checkout@v2
        if: steps.cache-repos.outputs.cache-hit != 'true'
        with:
          repository: 'opencv/opencv'
          ref: '4.3.0'
          path: tools/repos/opencv

      - name: Restore node modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            package-lock.json
          key: npm-install-${{ matrix.node-version }}-${{ hashFiles('package.json') }}

      - name: npm install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: npm run audit
        run: npm run audit

      - name: Download remaining dependencies
        run: npm run depends-checkout -- -j10

      - name: Restore dependency build files
        uses: actions/cache@v2
        with:
          path: |
            tools/build
          key: build-${{ matrix.os }}-${{ hashFiles('tools/manifest.mk') }}

      - name: Build dependencies
        run: npm run depends-build -- -j2

      - name: Install dependencies
        run: npm run depends-install

      - name: npm run build
        run: npm run build

      - name: npm test
        run: npm test
